### ISSUE TITLE
Can I set this to autoboot into Option 1?

### ISSUE THREAD

**Issue by DerpyBubblez** [ElXreno/archlinux-bootia32#3]
I'm trying to use this on my computer but my system's UEFI and GRUB don't recognize my USB keyboard. I can get around my UEFI by touching the screen, but for obvious reasons, that doesn't apply to GRUB.

**Comment by ElXreno** [comment]
I think you can add `set default=0` and `set timeout=5` before menuentries. You can put in whatever values you need.

**Comment by DerpyBubblez** [comment]
In the grub.cfg in the repo?

**Comment by ElXreno** [comment]
Yes. You can fork this repository, apply your changes, and wait for Github Actions.

**Comment by DerpyBubblez** [comment]
I completed the build process locally, and the  resulting file does work, but it seems that this thing refuses to even boot Arch properly.
